name: "FiatUconnect"
url: "https://github.com/Blueion76/FiatUconnect"
description: "Connect your FIAT (uconnect) car to Home Assistant. 🚗 Fork by Blueion"
services:
    - "mqtt:want"
version: "1.0"
homeassistant_api: true
image: "ghcr.io/blueion76/image-{arch}-fiat-uconnect"
slug: "fiat_uconnect"
init: false
discovery: 
    - "mqtt"
options:
  FiatUser: ""
  FiatPw: ""
  FiatPin: ""

  Brand: "Fiat"
  Region: "Europe"
  
  RefreshInterval: 2
  Debug: false
  AutoDeepRefresh: false
  AutoDeepInterval: 15

  StartDelaySeconds: 2
schema:
  FiatUser: str
  FiatPw: password
  FiatPin: password?

  Brand: list(Fiat|AlfaRomeo|Jeep|Debug)
  Region: list(Europe|US)
  
  RefreshInterval: int
  Debug: bool
  AutoDeepRefresh: bool
  AutoDeepInterval: int
  OverrideMqttUser: str?
  OverrideMqttPw: password?
  OverrideMqttServer: str?
  OverrideMqttPort: int?
  StartDelaySeconds: int?
arch:
  - amd64
  - armv7  

