name: "FCAUconnect"
url: "https://github.com/Blueion76/FCAUconnect-HA"
description: "Uconnect Home Assistant Addon for FCA vehicles (Jeep, Dodge, AlfaRomeo etc.)"
services:
    - "mqtt:want"
version: "1.1.1"
homeassistant_api: true
image: "ghcr.io/blueion76/image-{arch}-fca-uconnect"
slug: "fca_uconnect"
init: false
discovery: 
    - "mqtt"
options:
  FCAUser: ""
  FCAPw: ""
  FCAPin: ""
  Brand: "Jeep"
  RefreshInterval: 2
  ConvertKmtoMiles: false
  Debug: false
  AutoRefreshLocation: false
  AutoRefreshBattery: false
  carUnknownLocation: "away"
  StartDelaySeconds: 2
schema:
  FCAUser: str
  FCAPw: password
  FCAPin: password?
  Brand: list(Fiat|Ram|Jeep|Dodge|AlfaRomeo)
  Region: list(Europe|America)
  RefreshInterval: int
  Debug: bool
  AutoRefreshBattery: bool
  AutoRefreshLocation: bool
  OverrideMqttUser: str?
  OverrideMqttPw: password?
  OverrideMqttServer: str?
  OverrideMqttPort: int?
  CarUnknownLocation: str
  StartDelaySeconds: int?
arch:
  - amd64
  - armv7  

